services:
  frontend:
    build: ./frontend
    ports:
      - "5173:80"
  backend:
    build: ./backend
    env_file:
      - ./backend/.env.development.local
    ports:
      - "3000:3000"
    depends_on:
      - db
  db:
    image: postgres:16
    env_file:
      - ./backend/.env.development.local
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
      - ./backend/src/database/init:/docker-entrypoint-initdb.d
  db_test:
    image: postgres:16
    profiles: ["test"]
    env_file:
      - ./backend/.env.test.local
    ports:
      - "5434:5432"
    tmpfs:
      - /var/lib/postgresql
volumes:
  postgres_data:
